settings:
  application:
    # dev开发环境 test测试环境 prod线上环境
    mode: dev
    # 服务器ip，默认使用 0.0.0.0
    host: 0.0.0.0
    # 服务名称
    name: dh-passwd
    # 端口号
    port: 8080 # 服务端口号
    readtimeout: 1
    writertimeout: 2
  logger:
    # 日志存放路径
    path: data/logs
    # 控制台日志F
    stdout: true
    # 日志等级
    level: all
    enabledWeb: true
    # 数据库日志开关 dev模式，将自动开启
    enabledDb: true
  database:
    dbGen: dhpasswd
    # 数据库类型 mysql，sqlite3， postgres
    driver: mysql
    # 数据库连接字符串 mysql 缺省信息 charset=utf8&parseTime=True&loc=Local&timeout=1000ms
    source: passwd_admin:123456@tcp(127.0.0.1:3306)/dh_passwd_db?charset=utf8&parseTime=True&loc=Local&timeout=1000ms
    # source: DB/backend.db
  gen:
    # 代码生成读取的数据库名称
    dbname: dh-passwd
  jwt:
    # token 密钥，生产环境时及的修改
    secret: dh-passwd
    # token 过期时间 单位：秒
    timeout: 36000
  upload:
    # 数据存放路径
    path: data/upload/
